// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbpxpvxhbsweolohcwzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImticHhwdnhoYnN3ZW9sb2hjd3p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzOTAxNDEsImV4cCI6MjA3Njk2NjE0MX0.0sRSX4B3uJvq2EaTVb33nbjRg9Ytep_R4VEn8QxuWJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});